spring:
   datasource:
      url: jdbc:mysql://localhost:3306/develog-m?useSSL=false&serverTimezone=UTC
      username: root
      password: hyukjae

   ## Hibernate Properties
   # The SQL dialect makes Hibernate generate better SQL for the chosen database
   jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect